version: '3.9'

services:
  database:
    image: postgres
    container_name: database_maza
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=maza
    volumes:
      - pgdata:/data/postgres

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379

  app:
    build: .
    container_name: maza-system-backend
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
